// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateRecord implements createRecord operation.
//
// Create a new record.
//
// POST /records
func (UnimplementedHandler) CreateRecord(ctx context.Context, req *CreateRecordRequest) (r CreateRecordRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteRecord implements deleteRecord operation.
//
// Delete a record.
//
// DELETE /records/{id}
func (UnimplementedHandler) DeleteRecord(ctx context.Context, params DeleteRecordParams) (r DeleteRecordRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOidcConfig implements getOidcConfig operation.
//
// Get OIDC configuration for the frontend.
//
// GET /oidc-config
func (UnimplementedHandler) GetOidcConfig(ctx context.Context) (r *OIDCConfigResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRecommend implements getRecommend operation.
//
// Get recommendation score for a bean.
//
// GET /recommend
func (UnimplementedHandler) GetRecommend(ctx context.Context, params GetRecommendParams) (r GetRecommendRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRecord implements getRecord operation.
//
// Get a record by ID.
//
// GET /records/{id}
func (UnimplementedHandler) GetRecord(ctx context.Context, params GetRecordParams) (r GetRecordRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStatsFlavorWords implements getStatsFlavorWords operation.
//
// Get flavor word frequency.
//
// GET /stats/flavor-words
func (UnimplementedHandler) GetStatsFlavorWords(ctx context.Context) (r GetStatsFlavorWordsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStatsSummary implements getStatsSummary operation.
//
// Get statistics summary.
//
// GET /stats/summary
func (UnimplementedHandler) GetStatsSummary(ctx context.Context) (r GetStatsSummaryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserinfo implements getUserinfo operation.
//
// Get current user info (proxied from OIDC provider, or dummy in disable-oidc mode).
//
// GET /userinfo
func (UnimplementedHandler) GetUserinfo(ctx context.Context) (r GetUserinfoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListRecords implements listRecords operation.
//
// List records.
//
// GET /records
func (UnimplementedHandler) ListRecords(ctx context.Context, params ListRecordsParams) (r ListRecordsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateRecord implements updateRecord operation.
//
// Update a record.
//
// PUT /records/{id}
func (UnimplementedHandler) UpdateRecord(ctx context.Context, req *UpdateRecordRequest, params UpdateRecordParams) (r UpdateRecordRes, _ error) {
	return r, ht.ErrNotImplemented
}
