// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateRecord implements createRecord operation.
	//
	// Create a new record.
	//
	// POST /records
	CreateRecord(ctx context.Context, req *CreateRecordRequest) (CreateRecordRes, error)
	// DeleteRecord implements deleteRecord operation.
	//
	// Delete a record.
	//
	// DELETE /records/{id}
	DeleteRecord(ctx context.Context, params DeleteRecordParams) (DeleteRecordRes, error)
	// GetRecommend implements getRecommend operation.
	//
	// Get recommendation score for a bean.
	//
	// GET /recommend
	GetRecommend(ctx context.Context, params GetRecommendParams) (GetRecommendRes, error)
	// GetRecord implements getRecord operation.
	//
	// Get a record by ID.
	//
	// GET /records/{id}
	GetRecord(ctx context.Context, params GetRecordParams) (GetRecordRes, error)
	// GetStatsFlavorWords implements getStatsFlavorWords operation.
	//
	// Get flavor word frequency.
	//
	// GET /stats/flavor-words
	GetStatsFlavorWords(ctx context.Context) (GetStatsFlavorWordsRes, error)
	// GetStatsSummary implements getStatsSummary operation.
	//
	// Get statistics summary.
	//
	// GET /stats/summary
	GetStatsSummary(ctx context.Context) (GetStatsSummaryRes, error)
	// GetUserinfo implements getUserinfo operation.
	//
	// Get current user info (proxied from OIDC provider, or dummy in disable-oidc mode).
	//
	// GET /userinfo
	GetUserinfo(ctx context.Context) (GetUserinfoRes, error)
	// ListRecords implements listRecords operation.
	//
	// List records.
	//
	// GET /records
	ListRecords(ctx context.Context, params ListRecordsParams) (ListRecordsRes, error)
	// UpdateRecord implements updateRecord operation.
	//
	// Update a record.
	//
	// PUT /records/{id}
	UpdateRecord(ctx context.Context, req *UpdateRecordRequest, params UpdateRecordParams) (UpdateRecordRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
