// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// DeleteRecordParams is parameters of deleteRecord operation.
type DeleteRecordParams struct {
	ID int64
}

func unpackDeleteRecordParams(packed middleware.Parameters) (params DeleteRecordParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int64)
	}
	return params
}

func decodeDeleteRecordParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteRecordParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetRecommendParams is parameters of getRecommend operation.
type GetRecommendParams struct {
	Origin OptString `json:",omitempty,omitzero"`
	Name   OptString `json:",omitempty,omitzero"`
}

func unpackGetRecommendParams(packed middleware.Parameters) (params GetRecommendParams) {
	{
		key := middleware.ParameterKey{
			Name: "origin",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Origin = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "name",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Name = v.(OptString)
		}
	}
	return params
}

func decodeGetRecommendParams(args [0]string, argsEscaped bool, r *http.Request) (params GetRecommendParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: origin.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "origin",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotOriginVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotOriginVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Origin.SetTo(paramsDotOriginVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "origin",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: name.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "name",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotNameVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotNameVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Name.SetTo(paramsDotNameVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "name",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetRecordParams is parameters of getRecord operation.
type GetRecordParams struct {
	ID int64
}

func unpackGetRecordParams(packed middleware.Parameters) (params GetRecordParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int64)
	}
	return params
}

func decodeGetRecordParams(args [1]string, argsEscaped bool, r *http.Request) (params GetRecordParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListRecordsParams is parameters of listRecords operation.
type ListRecordsParams struct {
	Origin     OptString                `json:",omitempty,omitzero"`
	RoastLevel OptListRecordsRoastLevel `json:",omitempty,omitzero"`
	RatingMin  OptInt                   `json:",omitempty,omitzero"`
	BrewMethod OptListRecordsBrewMethod `json:",omitempty,omitzero"`
}

func unpackListRecordsParams(packed middleware.Parameters) (params ListRecordsParams) {
	{
		key := middleware.ParameterKey{
			Name: "origin",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Origin = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "roast_level",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.RoastLevel = v.(OptListRecordsRoastLevel)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "rating_min",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.RatingMin = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "brew_method",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.BrewMethod = v.(OptListRecordsBrewMethod)
		}
	}
	return params
}

func decodeListRecordsParams(args [0]string, argsEscaped bool, r *http.Request) (params ListRecordsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: origin.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "origin",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotOriginVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotOriginVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Origin.SetTo(paramsDotOriginVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "origin",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: roast_level.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "roast_level",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotRoastLevelVal ListRecordsRoastLevel
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotRoastLevelVal = ListRecordsRoastLevel(c)
					return nil
				}(); err != nil {
					return err
				}
				params.RoastLevel.SetTo(paramsDotRoastLevelVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.RoastLevel.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "roast_level",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: rating_min.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "rating_min",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotRatingMinVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotRatingMinVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.RatingMin.SetTo(paramsDotRatingMinVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.RatingMin.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           5,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "rating_min",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: brew_method.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "brew_method",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotBrewMethodVal ListRecordsBrewMethod
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotBrewMethodVal = ListRecordsBrewMethod(c)
					return nil
				}(); err != nil {
					return err
				}
				params.BrewMethod.SetTo(paramsDotBrewMethodVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.BrewMethod.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "brew_method",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateRecordParams is parameters of updateRecord operation.
type UpdateRecordParams struct {
	ID int64
}

func unpackUpdateRecordParams(packed middleware.Parameters) (params UpdateRecordParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int64)
	}
	return params
}

func decodeUpdateRecordParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateRecordParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
