// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/go-faster/errors"
)

type CreateRecordBadRequest Error

func (*CreateRecordBadRequest) createRecordRes() {}

type CreateRecordInternalServerError Error

func (*CreateRecordInternalServerError) createRecordRes() {}

// Ref: #/components/schemas/CreateRecordRequest
type CreateRecordRequest struct {
	Name        string                              `json:"name"`
	Rating      OptInt                              `json:"rating"`
	Origin      OptNilString                        `json:"origin"`
	RoastLevel  OptNilCreateRecordRequestRoastLevel `json:"roast_level"`
	Shop        OptNilString                        `json:"shop"`
	Price       OptNilInt                           `json:"price"`
	PurchasedAt OptNilDate                          `json:"purchased_at"`
	TastingNote OptNilString                        `json:"tasting_note"`
	BrewMethod  OptNilCreateRecordRequestBrewMethod `json:"brew_method"`
	Recipe      OptNilString                        `json:"recipe"`
}

// GetName returns the value of Name.
func (s *CreateRecordRequest) GetName() string {
	return s.Name
}

// GetRating returns the value of Rating.
func (s *CreateRecordRequest) GetRating() OptInt {
	return s.Rating
}

// GetOrigin returns the value of Origin.
func (s *CreateRecordRequest) GetOrigin() OptNilString {
	return s.Origin
}

// GetRoastLevel returns the value of RoastLevel.
func (s *CreateRecordRequest) GetRoastLevel() OptNilCreateRecordRequestRoastLevel {
	return s.RoastLevel
}

// GetShop returns the value of Shop.
func (s *CreateRecordRequest) GetShop() OptNilString {
	return s.Shop
}

// GetPrice returns the value of Price.
func (s *CreateRecordRequest) GetPrice() OptNilInt {
	return s.Price
}

// GetPurchasedAt returns the value of PurchasedAt.
func (s *CreateRecordRequest) GetPurchasedAt() OptNilDate {
	return s.PurchasedAt
}

// GetTastingNote returns the value of TastingNote.
func (s *CreateRecordRequest) GetTastingNote() OptNilString {
	return s.TastingNote
}

// GetBrewMethod returns the value of BrewMethod.
func (s *CreateRecordRequest) GetBrewMethod() OptNilCreateRecordRequestBrewMethod {
	return s.BrewMethod
}

// GetRecipe returns the value of Recipe.
func (s *CreateRecordRequest) GetRecipe() OptNilString {
	return s.Recipe
}

// SetName sets the value of Name.
func (s *CreateRecordRequest) SetName(val string) {
	s.Name = val
}

// SetRating sets the value of Rating.
func (s *CreateRecordRequest) SetRating(val OptInt) {
	s.Rating = val
}

// SetOrigin sets the value of Origin.
func (s *CreateRecordRequest) SetOrigin(val OptNilString) {
	s.Origin = val
}

// SetRoastLevel sets the value of RoastLevel.
func (s *CreateRecordRequest) SetRoastLevel(val OptNilCreateRecordRequestRoastLevel) {
	s.RoastLevel = val
}

// SetShop sets the value of Shop.
func (s *CreateRecordRequest) SetShop(val OptNilString) {
	s.Shop = val
}

// SetPrice sets the value of Price.
func (s *CreateRecordRequest) SetPrice(val OptNilInt) {
	s.Price = val
}

// SetPurchasedAt sets the value of PurchasedAt.
func (s *CreateRecordRequest) SetPurchasedAt(val OptNilDate) {
	s.PurchasedAt = val
}

// SetTastingNote sets the value of TastingNote.
func (s *CreateRecordRequest) SetTastingNote(val OptNilString) {
	s.TastingNote = val
}

// SetBrewMethod sets the value of BrewMethod.
func (s *CreateRecordRequest) SetBrewMethod(val OptNilCreateRecordRequestBrewMethod) {
	s.BrewMethod = val
}

// SetRecipe sets the value of Recipe.
func (s *CreateRecordRequest) SetRecipe(val OptNilString) {
	s.Recipe = val
}

type CreateRecordRequestBrewMethod string

const (
	CreateRecordRequestBrewMethodDrip        CreateRecordRequestBrewMethod = "drip"
	CreateRecordRequestBrewMethodEspresso    CreateRecordRequestBrewMethod = "espresso"
	CreateRecordRequestBrewMethodFrenchPress CreateRecordRequestBrewMethod = "french_press"
	CreateRecordRequestBrewMethodOther       CreateRecordRequestBrewMethod = "other"
)

// AllValues returns all CreateRecordRequestBrewMethod values.
func (CreateRecordRequestBrewMethod) AllValues() []CreateRecordRequestBrewMethod {
	return []CreateRecordRequestBrewMethod{
		CreateRecordRequestBrewMethodDrip,
		CreateRecordRequestBrewMethodEspresso,
		CreateRecordRequestBrewMethodFrenchPress,
		CreateRecordRequestBrewMethodOther,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateRecordRequestBrewMethod) MarshalText() ([]byte, error) {
	switch s {
	case CreateRecordRequestBrewMethodDrip:
		return []byte(s), nil
	case CreateRecordRequestBrewMethodEspresso:
		return []byte(s), nil
	case CreateRecordRequestBrewMethodFrenchPress:
		return []byte(s), nil
	case CreateRecordRequestBrewMethodOther:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateRecordRequestBrewMethod) UnmarshalText(data []byte) error {
	switch CreateRecordRequestBrewMethod(data) {
	case CreateRecordRequestBrewMethodDrip:
		*s = CreateRecordRequestBrewMethodDrip
		return nil
	case CreateRecordRequestBrewMethodEspresso:
		*s = CreateRecordRequestBrewMethodEspresso
		return nil
	case CreateRecordRequestBrewMethodFrenchPress:
		*s = CreateRecordRequestBrewMethodFrenchPress
		return nil
	case CreateRecordRequestBrewMethodOther:
		*s = CreateRecordRequestBrewMethodOther
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CreateRecordRequestRoastLevel string

const (
	CreateRecordRequestRoastLevelLight  CreateRecordRequestRoastLevel = "light"
	CreateRecordRequestRoastLevelMedium CreateRecordRequestRoastLevel = "medium"
	CreateRecordRequestRoastLevelDark   CreateRecordRequestRoastLevel = "dark"
)

// AllValues returns all CreateRecordRequestRoastLevel values.
func (CreateRecordRequestRoastLevel) AllValues() []CreateRecordRequestRoastLevel {
	return []CreateRecordRequestRoastLevel{
		CreateRecordRequestRoastLevelLight,
		CreateRecordRequestRoastLevelMedium,
		CreateRecordRequestRoastLevelDark,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateRecordRequestRoastLevel) MarshalText() ([]byte, error) {
	switch s {
	case CreateRecordRequestRoastLevelLight:
		return []byte(s), nil
	case CreateRecordRequestRoastLevelMedium:
		return []byte(s), nil
	case CreateRecordRequestRoastLevelDark:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateRecordRequestRoastLevel) UnmarshalText(data []byte) error {
	switch CreateRecordRequestRoastLevel(data) {
	case CreateRecordRequestRoastLevelLight:
		*s = CreateRecordRequestRoastLevelLight
		return nil
	case CreateRecordRequestRoastLevelMedium:
		*s = CreateRecordRequestRoastLevelMedium
		return nil
	case CreateRecordRequestRoastLevelDark:
		*s = CreateRecordRequestRoastLevelDark
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type DeleteRecordInternalServerError Error

func (*DeleteRecordInternalServerError) deleteRecordRes() {}

// DeleteRecordNoContent is response for DeleteRecord operation.
type DeleteRecordNoContent struct{}

func (*DeleteRecordNoContent) deleteRecordRes() {}

type DeleteRecordNotFound Error

func (*DeleteRecordNotFound) deleteRecordRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

func (*Error) getRecommendRes()        {}
func (*Error) getStatsFlavorWordsRes() {}
func (*Error) getStatsSummaryRes()     {}
func (*Error) listRecordsRes()         {}

// Ref: #/components/schemas/FlavorWord
type FlavorWord struct {
	Word  string `json:"word"`
	Count int    `json:"count"`
}

// GetWord returns the value of Word.
func (s *FlavorWord) GetWord() string {
	return s.Word
}

// GetCount returns the value of Count.
func (s *FlavorWord) GetCount() int {
	return s.Count
}

// SetWord sets the value of Word.
func (s *FlavorWord) SetWord(val string) {
	s.Word = val
}

// SetCount sets the value of Count.
func (s *FlavorWord) SetCount(val int) {
	s.Count = val
}

type GetRecordInternalServerError Error

func (*GetRecordInternalServerError) getRecordRes() {}

type GetRecordNotFound Error

func (*GetRecordNotFound) getRecordRes() {}

type GetStatsFlavorWordsOKApplicationJSON []FlavorWord

func (*GetStatsFlavorWordsOKApplicationJSON) getStatsFlavorWordsRes() {}

// Ref: #/components/schemas/GroupStat
type GroupStat struct {
	Label     string  `json:"label"`
	Count     int     `json:"count"`
	AvgRating float32 `json:"avg_rating"`
}

// GetLabel returns the value of Label.
func (s *GroupStat) GetLabel() string {
	return s.Label
}

// GetCount returns the value of Count.
func (s *GroupStat) GetCount() int {
	return s.Count
}

// GetAvgRating returns the value of AvgRating.
func (s *GroupStat) GetAvgRating() float32 {
	return s.AvgRating
}

// SetLabel sets the value of Label.
func (s *GroupStat) SetLabel(val string) {
	s.Label = val
}

// SetCount sets the value of Count.
func (s *GroupStat) SetCount(val int) {
	s.Count = val
}

// SetAvgRating sets the value of AvgRating.
func (s *GroupStat) SetAvgRating(val float32) {
	s.AvgRating = val
}

type ListRecordsBrewMethod string

const (
	ListRecordsBrewMethodDrip        ListRecordsBrewMethod = "drip"
	ListRecordsBrewMethodEspresso    ListRecordsBrewMethod = "espresso"
	ListRecordsBrewMethodFrenchPress ListRecordsBrewMethod = "french_press"
	ListRecordsBrewMethodOther       ListRecordsBrewMethod = "other"
)

// AllValues returns all ListRecordsBrewMethod values.
func (ListRecordsBrewMethod) AllValues() []ListRecordsBrewMethod {
	return []ListRecordsBrewMethod{
		ListRecordsBrewMethodDrip,
		ListRecordsBrewMethodEspresso,
		ListRecordsBrewMethodFrenchPress,
		ListRecordsBrewMethodOther,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ListRecordsBrewMethod) MarshalText() ([]byte, error) {
	switch s {
	case ListRecordsBrewMethodDrip:
		return []byte(s), nil
	case ListRecordsBrewMethodEspresso:
		return []byte(s), nil
	case ListRecordsBrewMethodFrenchPress:
		return []byte(s), nil
	case ListRecordsBrewMethodOther:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ListRecordsBrewMethod) UnmarshalText(data []byte) error {
	switch ListRecordsBrewMethod(data) {
	case ListRecordsBrewMethodDrip:
		*s = ListRecordsBrewMethodDrip
		return nil
	case ListRecordsBrewMethodEspresso:
		*s = ListRecordsBrewMethodEspresso
		return nil
	case ListRecordsBrewMethodFrenchPress:
		*s = ListRecordsBrewMethodFrenchPress
		return nil
	case ListRecordsBrewMethodOther:
		*s = ListRecordsBrewMethodOther
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ListRecordsOKApplicationJSON []Record

func (*ListRecordsOKApplicationJSON) listRecordsRes() {}

type ListRecordsRoastLevel string

const (
	ListRecordsRoastLevelLight  ListRecordsRoastLevel = "light"
	ListRecordsRoastLevelMedium ListRecordsRoastLevel = "medium"
	ListRecordsRoastLevelDark   ListRecordsRoastLevel = "dark"
)

// AllValues returns all ListRecordsRoastLevel values.
func (ListRecordsRoastLevel) AllValues() []ListRecordsRoastLevel {
	return []ListRecordsRoastLevel{
		ListRecordsRoastLevelLight,
		ListRecordsRoastLevelMedium,
		ListRecordsRoastLevelDark,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ListRecordsRoastLevel) MarshalText() ([]byte, error) {
	switch s {
	case ListRecordsRoastLevelLight:
		return []byte(s), nil
	case ListRecordsRoastLevelMedium:
		return []byte(s), nil
	case ListRecordsRoastLevelDark:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ListRecordsRoastLevel) UnmarshalText(data []byte) error {
	switch ListRecordsRoastLevel(data) {
	case ListRecordsRoastLevelLight:
		*s = ListRecordsRoastLevelLight
		return nil
	case ListRecordsRoastLevelMedium:
		*s = ListRecordsRoastLevelMedium
		return nil
	case ListRecordsRoastLevelDark:
		*s = ListRecordsRoastLevelDark
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptListRecordsBrewMethod returns new OptListRecordsBrewMethod with value set to v.
func NewOptListRecordsBrewMethod(v ListRecordsBrewMethod) OptListRecordsBrewMethod {
	return OptListRecordsBrewMethod{
		Value: v,
		Set:   true,
	}
}

// OptListRecordsBrewMethod is optional ListRecordsBrewMethod.
type OptListRecordsBrewMethod struct {
	Value ListRecordsBrewMethod
	Set   bool
}

// IsSet returns true if OptListRecordsBrewMethod was set.
func (o OptListRecordsBrewMethod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptListRecordsBrewMethod) Reset() {
	var v ListRecordsBrewMethod
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptListRecordsBrewMethod) SetTo(v ListRecordsBrewMethod) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptListRecordsBrewMethod) Get() (v ListRecordsBrewMethod, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptListRecordsBrewMethod) Or(d ListRecordsBrewMethod) ListRecordsBrewMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptListRecordsRoastLevel returns new OptListRecordsRoastLevel with value set to v.
func NewOptListRecordsRoastLevel(v ListRecordsRoastLevel) OptListRecordsRoastLevel {
	return OptListRecordsRoastLevel{
		Value: v,
		Set:   true,
	}
}

// OptListRecordsRoastLevel is optional ListRecordsRoastLevel.
type OptListRecordsRoastLevel struct {
	Value ListRecordsRoastLevel
	Set   bool
}

// IsSet returns true if OptListRecordsRoastLevel was set.
func (o OptListRecordsRoastLevel) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptListRecordsRoastLevel) Reset() {
	var v ListRecordsRoastLevel
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptListRecordsRoastLevel) SetTo(v ListRecordsRoastLevel) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptListRecordsRoastLevel) Get() (v ListRecordsRoastLevel, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptListRecordsRoastLevel) Or(d ListRecordsRoastLevel) ListRecordsRoastLevel {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilCreateRecordRequestBrewMethod returns new OptNilCreateRecordRequestBrewMethod with value set to v.
func NewOptNilCreateRecordRequestBrewMethod(v CreateRecordRequestBrewMethod) OptNilCreateRecordRequestBrewMethod {
	return OptNilCreateRecordRequestBrewMethod{
		Value: v,
		Set:   true,
	}
}

// OptNilCreateRecordRequestBrewMethod is optional nullable CreateRecordRequestBrewMethod.
type OptNilCreateRecordRequestBrewMethod struct {
	Value CreateRecordRequestBrewMethod
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilCreateRecordRequestBrewMethod was set.
func (o OptNilCreateRecordRequestBrewMethod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilCreateRecordRequestBrewMethod) Reset() {
	var v CreateRecordRequestBrewMethod
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilCreateRecordRequestBrewMethod) SetTo(v CreateRecordRequestBrewMethod) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilCreateRecordRequestBrewMethod) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilCreateRecordRequestBrewMethod) SetToNull() {
	o.Set = true
	o.Null = true
	var v CreateRecordRequestBrewMethod
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilCreateRecordRequestBrewMethod) Get() (v CreateRecordRequestBrewMethod, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilCreateRecordRequestBrewMethod) Or(d CreateRecordRequestBrewMethod) CreateRecordRequestBrewMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilCreateRecordRequestRoastLevel returns new OptNilCreateRecordRequestRoastLevel with value set to v.
func NewOptNilCreateRecordRequestRoastLevel(v CreateRecordRequestRoastLevel) OptNilCreateRecordRequestRoastLevel {
	return OptNilCreateRecordRequestRoastLevel{
		Value: v,
		Set:   true,
	}
}

// OptNilCreateRecordRequestRoastLevel is optional nullable CreateRecordRequestRoastLevel.
type OptNilCreateRecordRequestRoastLevel struct {
	Value CreateRecordRequestRoastLevel
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilCreateRecordRequestRoastLevel was set.
func (o OptNilCreateRecordRequestRoastLevel) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilCreateRecordRequestRoastLevel) Reset() {
	var v CreateRecordRequestRoastLevel
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilCreateRecordRequestRoastLevel) SetTo(v CreateRecordRequestRoastLevel) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilCreateRecordRequestRoastLevel) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilCreateRecordRequestRoastLevel) SetToNull() {
	o.Set = true
	o.Null = true
	var v CreateRecordRequestRoastLevel
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilCreateRecordRequestRoastLevel) Get() (v CreateRecordRequestRoastLevel, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilCreateRecordRequestRoastLevel) Or(d CreateRecordRequestRoastLevel) CreateRecordRequestRoastLevel {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDate returns new OptNilDate with value set to v.
func NewOptNilDate(v time.Time) OptNilDate {
	return OptNilDate{
		Value: v,
		Set:   true,
	}
}

// OptNilDate is optional nullable time.Time.
type OptNilDate struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDate was set.
func (o OptNilDate) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDate) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDate) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDate) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDate) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDate) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDate) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilFloat32 returns new OptNilFloat32 with value set to v.
func NewOptNilFloat32(v float32) OptNilFloat32 {
	return OptNilFloat32{
		Value: v,
		Set:   true,
	}
}

// OptNilFloat32 is optional nullable float32.
type OptNilFloat32 struct {
	Value float32
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilFloat32 was set.
func (o OptNilFloat32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilFloat32) Reset() {
	var v float32
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilFloat32) SetTo(v float32) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilFloat32) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilFloat32) SetToNull() {
	o.Set = true
	o.Null = true
	var v float32
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilFloat32) Get() (v float32, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilFloat32) Or(d float32) float32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilInt returns new OptNilInt with value set to v.
func NewOptNilInt(v int) OptNilInt {
	return OptNilInt{
		Value: v,
		Set:   true,
	}
}

// OptNilInt is optional nullable int.
type OptNilInt struct {
	Value int
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilInt was set.
func (o OptNilInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilInt) SetTo(v int) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilInt) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilInt) SetToNull() {
	o.Set = true
	o.Null = true
	var v int
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilInt) Get() (v int, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilRecordBrewMethod returns new OptNilRecordBrewMethod with value set to v.
func NewOptNilRecordBrewMethod(v RecordBrewMethod) OptNilRecordBrewMethod {
	return OptNilRecordBrewMethod{
		Value: v,
		Set:   true,
	}
}

// OptNilRecordBrewMethod is optional nullable RecordBrewMethod.
type OptNilRecordBrewMethod struct {
	Value RecordBrewMethod
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilRecordBrewMethod was set.
func (o OptNilRecordBrewMethod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilRecordBrewMethod) Reset() {
	var v RecordBrewMethod
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilRecordBrewMethod) SetTo(v RecordBrewMethod) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilRecordBrewMethod) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilRecordBrewMethod) SetToNull() {
	o.Set = true
	o.Null = true
	var v RecordBrewMethod
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilRecordBrewMethod) Get() (v RecordBrewMethod, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilRecordBrewMethod) Or(d RecordBrewMethod) RecordBrewMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilRecordDetailBrewMethod returns new OptNilRecordDetailBrewMethod with value set to v.
func NewOptNilRecordDetailBrewMethod(v RecordDetailBrewMethod) OptNilRecordDetailBrewMethod {
	return OptNilRecordDetailBrewMethod{
		Value: v,
		Set:   true,
	}
}

// OptNilRecordDetailBrewMethod is optional nullable RecordDetailBrewMethod.
type OptNilRecordDetailBrewMethod struct {
	Value RecordDetailBrewMethod
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilRecordDetailBrewMethod was set.
func (o OptNilRecordDetailBrewMethod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilRecordDetailBrewMethod) Reset() {
	var v RecordDetailBrewMethod
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilRecordDetailBrewMethod) SetTo(v RecordDetailBrewMethod) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilRecordDetailBrewMethod) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilRecordDetailBrewMethod) SetToNull() {
	o.Set = true
	o.Null = true
	var v RecordDetailBrewMethod
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilRecordDetailBrewMethod) Get() (v RecordDetailBrewMethod, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilRecordDetailBrewMethod) Or(d RecordDetailBrewMethod) RecordDetailBrewMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilRecordDetailRoastLevel returns new OptNilRecordDetailRoastLevel with value set to v.
func NewOptNilRecordDetailRoastLevel(v RecordDetailRoastLevel) OptNilRecordDetailRoastLevel {
	return OptNilRecordDetailRoastLevel{
		Value: v,
		Set:   true,
	}
}

// OptNilRecordDetailRoastLevel is optional nullable RecordDetailRoastLevel.
type OptNilRecordDetailRoastLevel struct {
	Value RecordDetailRoastLevel
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilRecordDetailRoastLevel was set.
func (o OptNilRecordDetailRoastLevel) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilRecordDetailRoastLevel) Reset() {
	var v RecordDetailRoastLevel
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilRecordDetailRoastLevel) SetTo(v RecordDetailRoastLevel) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilRecordDetailRoastLevel) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilRecordDetailRoastLevel) SetToNull() {
	o.Set = true
	o.Null = true
	var v RecordDetailRoastLevel
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilRecordDetailRoastLevel) Get() (v RecordDetailRoastLevel, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilRecordDetailRoastLevel) Or(d RecordDetailRoastLevel) RecordDetailRoastLevel {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilRecordRoastLevel returns new OptNilRecordRoastLevel with value set to v.
func NewOptNilRecordRoastLevel(v RecordRoastLevel) OptNilRecordRoastLevel {
	return OptNilRecordRoastLevel{
		Value: v,
		Set:   true,
	}
}

// OptNilRecordRoastLevel is optional nullable RecordRoastLevel.
type OptNilRecordRoastLevel struct {
	Value RecordRoastLevel
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilRecordRoastLevel was set.
func (o OptNilRecordRoastLevel) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilRecordRoastLevel) Reset() {
	var v RecordRoastLevel
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilRecordRoastLevel) SetTo(v RecordRoastLevel) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilRecordRoastLevel) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilRecordRoastLevel) SetToNull() {
	o.Set = true
	o.Null = true
	var v RecordRoastLevel
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilRecordRoastLevel) Get() (v RecordRoastLevel, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilRecordRoastLevel) Or(d RecordRoastLevel) RecordRoastLevel {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilUpdateRecordRequestBrewMethod returns new OptNilUpdateRecordRequestBrewMethod with value set to v.
func NewOptNilUpdateRecordRequestBrewMethod(v UpdateRecordRequestBrewMethod) OptNilUpdateRecordRequestBrewMethod {
	return OptNilUpdateRecordRequestBrewMethod{
		Value: v,
		Set:   true,
	}
}

// OptNilUpdateRecordRequestBrewMethod is optional nullable UpdateRecordRequestBrewMethod.
type OptNilUpdateRecordRequestBrewMethod struct {
	Value UpdateRecordRequestBrewMethod
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilUpdateRecordRequestBrewMethod was set.
func (o OptNilUpdateRecordRequestBrewMethod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilUpdateRecordRequestBrewMethod) Reset() {
	var v UpdateRecordRequestBrewMethod
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilUpdateRecordRequestBrewMethod) SetTo(v UpdateRecordRequestBrewMethod) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilUpdateRecordRequestBrewMethod) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilUpdateRecordRequestBrewMethod) SetToNull() {
	o.Set = true
	o.Null = true
	var v UpdateRecordRequestBrewMethod
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilUpdateRecordRequestBrewMethod) Get() (v UpdateRecordRequestBrewMethod, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilUpdateRecordRequestBrewMethod) Or(d UpdateRecordRequestBrewMethod) UpdateRecordRequestBrewMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilUpdateRecordRequestRoastLevel returns new OptNilUpdateRecordRequestRoastLevel with value set to v.
func NewOptNilUpdateRecordRequestRoastLevel(v UpdateRecordRequestRoastLevel) OptNilUpdateRecordRequestRoastLevel {
	return OptNilUpdateRecordRequestRoastLevel{
		Value: v,
		Set:   true,
	}
}

// OptNilUpdateRecordRequestRoastLevel is optional nullable UpdateRecordRequestRoastLevel.
type OptNilUpdateRecordRequestRoastLevel struct {
	Value UpdateRecordRequestRoastLevel
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilUpdateRecordRequestRoastLevel was set.
func (o OptNilUpdateRecordRequestRoastLevel) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilUpdateRecordRequestRoastLevel) Reset() {
	var v UpdateRecordRequestRoastLevel
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilUpdateRecordRequestRoastLevel) SetTo(v UpdateRecordRequestRoastLevel) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilUpdateRecordRequestRoastLevel) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilUpdateRecordRequestRoastLevel) SetToNull() {
	o.Set = true
	o.Null = true
	var v UpdateRecordRequestRoastLevel
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilUpdateRecordRequestRoastLevel) Get() (v UpdateRecordRequestRoastLevel, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilUpdateRecordRequestRoastLevel) Or(d UpdateRecordRequestRoastLevel) UpdateRecordRequestRoastLevel {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/RecommendResult
type RecommendResult struct {
	Locked bool `json:"locked"`
	// How many more records needed to unlock (only when locked=true).
	RecordsNeeded OptNilInt `json:"records_needed"`
	// Preference score 0.0-5.0 (null when locked).
	Score        OptNilFloat32 `json:"score"`
	TotalRecords int           `json:"total_records"`
	OriginAvg    OptNilFloat32 `json:"origin_avg"`
	NameMatchAvg OptNilFloat32 `json:"name_match_avg"`
}

// GetLocked returns the value of Locked.
func (s *RecommendResult) GetLocked() bool {
	return s.Locked
}

// GetRecordsNeeded returns the value of RecordsNeeded.
func (s *RecommendResult) GetRecordsNeeded() OptNilInt {
	return s.RecordsNeeded
}

// GetScore returns the value of Score.
func (s *RecommendResult) GetScore() OptNilFloat32 {
	return s.Score
}

// GetTotalRecords returns the value of TotalRecords.
func (s *RecommendResult) GetTotalRecords() int {
	return s.TotalRecords
}

// GetOriginAvg returns the value of OriginAvg.
func (s *RecommendResult) GetOriginAvg() OptNilFloat32 {
	return s.OriginAvg
}

// GetNameMatchAvg returns the value of NameMatchAvg.
func (s *RecommendResult) GetNameMatchAvg() OptNilFloat32 {
	return s.NameMatchAvg
}

// SetLocked sets the value of Locked.
func (s *RecommendResult) SetLocked(val bool) {
	s.Locked = val
}

// SetRecordsNeeded sets the value of RecordsNeeded.
func (s *RecommendResult) SetRecordsNeeded(val OptNilInt) {
	s.RecordsNeeded = val
}

// SetScore sets the value of Score.
func (s *RecommendResult) SetScore(val OptNilFloat32) {
	s.Score = val
}

// SetTotalRecords sets the value of TotalRecords.
func (s *RecommendResult) SetTotalRecords(val int) {
	s.TotalRecords = val
}

// SetOriginAvg sets the value of OriginAvg.
func (s *RecommendResult) SetOriginAvg(val OptNilFloat32) {
	s.OriginAvg = val
}

// SetNameMatchAvg sets the value of NameMatchAvg.
func (s *RecommendResult) SetNameMatchAvg(val OptNilFloat32) {
	s.NameMatchAvg = val
}

func (*RecommendResult) getRecommendRes() {}

// Ref: #/components/schemas/Record
type Record struct {
	ID           int64                  `json:"id"`
	Name         string                 `json:"name"`
	Rating       int                    `json:"rating"`
	Origin       OptNilString           `json:"origin"`
	RoastLevel   OptNilRecordRoastLevel `json:"roast_level"`
	Shop         OptNilString           `json:"shop"`
	Price        OptNilInt              `json:"price"`
	PurchasedAt  OptNilDate             `json:"purchased_at"`
	TastingNote  OptNilString           `json:"tasting_note"`
	BrewMethod   OptNilRecordBrewMethod `json:"brew_method"`
	Recipe       OptNilString           `json:"recipe"`
	IsNoteFilled bool                   `json:"is_note_filled"`
	CreatedAt    time.Time              `json:"created_at"`
	UpdatedAt    time.Time              `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *Record) GetID() int64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *Record) GetName() string {
	return s.Name
}

// GetRating returns the value of Rating.
func (s *Record) GetRating() int {
	return s.Rating
}

// GetOrigin returns the value of Origin.
func (s *Record) GetOrigin() OptNilString {
	return s.Origin
}

// GetRoastLevel returns the value of RoastLevel.
func (s *Record) GetRoastLevel() OptNilRecordRoastLevel {
	return s.RoastLevel
}

// GetShop returns the value of Shop.
func (s *Record) GetShop() OptNilString {
	return s.Shop
}

// GetPrice returns the value of Price.
func (s *Record) GetPrice() OptNilInt {
	return s.Price
}

// GetPurchasedAt returns the value of PurchasedAt.
func (s *Record) GetPurchasedAt() OptNilDate {
	return s.PurchasedAt
}

// GetTastingNote returns the value of TastingNote.
func (s *Record) GetTastingNote() OptNilString {
	return s.TastingNote
}

// GetBrewMethod returns the value of BrewMethod.
func (s *Record) GetBrewMethod() OptNilRecordBrewMethod {
	return s.BrewMethod
}

// GetRecipe returns the value of Recipe.
func (s *Record) GetRecipe() OptNilString {
	return s.Recipe
}

// GetIsNoteFilled returns the value of IsNoteFilled.
func (s *Record) GetIsNoteFilled() bool {
	return s.IsNoteFilled
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Record) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Record) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Record) SetID(val int64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Record) SetName(val string) {
	s.Name = val
}

// SetRating sets the value of Rating.
func (s *Record) SetRating(val int) {
	s.Rating = val
}

// SetOrigin sets the value of Origin.
func (s *Record) SetOrigin(val OptNilString) {
	s.Origin = val
}

// SetRoastLevel sets the value of RoastLevel.
func (s *Record) SetRoastLevel(val OptNilRecordRoastLevel) {
	s.RoastLevel = val
}

// SetShop sets the value of Shop.
func (s *Record) SetShop(val OptNilString) {
	s.Shop = val
}

// SetPrice sets the value of Price.
func (s *Record) SetPrice(val OptNilInt) {
	s.Price = val
}

// SetPurchasedAt sets the value of PurchasedAt.
func (s *Record) SetPurchasedAt(val OptNilDate) {
	s.PurchasedAt = val
}

// SetTastingNote sets the value of TastingNote.
func (s *Record) SetTastingNote(val OptNilString) {
	s.TastingNote = val
}

// SetBrewMethod sets the value of BrewMethod.
func (s *Record) SetBrewMethod(val OptNilRecordBrewMethod) {
	s.BrewMethod = val
}

// SetRecipe sets the value of Recipe.
func (s *Record) SetRecipe(val OptNilString) {
	s.Recipe = val
}

// SetIsNoteFilled sets the value of IsNoteFilled.
func (s *Record) SetIsNoteFilled(val bool) {
	s.IsNoteFilled = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Record) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Record) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*Record) createRecordRes() {}
func (*Record) updateRecordRes() {}

type RecordBrewMethod string

const (
	RecordBrewMethodDrip        RecordBrewMethod = "drip"
	RecordBrewMethodEspresso    RecordBrewMethod = "espresso"
	RecordBrewMethodFrenchPress RecordBrewMethod = "french_press"
	RecordBrewMethodOther       RecordBrewMethod = "other"
)

// AllValues returns all RecordBrewMethod values.
func (RecordBrewMethod) AllValues() []RecordBrewMethod {
	return []RecordBrewMethod{
		RecordBrewMethodDrip,
		RecordBrewMethodEspresso,
		RecordBrewMethodFrenchPress,
		RecordBrewMethodOther,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s RecordBrewMethod) MarshalText() ([]byte, error) {
	switch s {
	case RecordBrewMethodDrip:
		return []byte(s), nil
	case RecordBrewMethodEspresso:
		return []byte(s), nil
	case RecordBrewMethodFrenchPress:
		return []byte(s), nil
	case RecordBrewMethodOther:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *RecordBrewMethod) UnmarshalText(data []byte) error {
	switch RecordBrewMethod(data) {
	case RecordBrewMethodDrip:
		*s = RecordBrewMethodDrip
		return nil
	case RecordBrewMethodEspresso:
		*s = RecordBrewMethodEspresso
		return nil
	case RecordBrewMethodFrenchPress:
		*s = RecordBrewMethodFrenchPress
		return nil
	case RecordBrewMethodOther:
		*s = RecordBrewMethodOther
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Merged schema.
// Ref: #/components/schemas/RecordDetail
type RecordDetail struct {
	ID           int64                        `json:"id"`
	Name         string                       `json:"name"`
	Rating       int                          `json:"rating"`
	Origin       OptNilString                 `json:"origin"`
	RoastLevel   OptNilRecordDetailRoastLevel `json:"roast_level"`
	Shop         OptNilString                 `json:"shop"`
	Price        OptNilInt                    `json:"price"`
	PurchasedAt  OptNilDate                   `json:"purchased_at"`
	TastingNote  OptNilString                 `json:"tasting_note"`
	BrewMethod   OptNilRecordDetailBrewMethod `json:"brew_method"`
	Recipe       OptNilString                 `json:"recipe"`
	IsNoteFilled bool                         `json:"is_note_filled"`
	CreatedAt    time.Time                    `json:"created_at"`
	UpdatedAt    time.Time                    `json:"updated_at"`
	// Other records of the same bean (same name or origin).
	RelatedRecords []Record `json:"related_records"`
}

// GetID returns the value of ID.
func (s *RecordDetail) GetID() int64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *RecordDetail) GetName() string {
	return s.Name
}

// GetRating returns the value of Rating.
func (s *RecordDetail) GetRating() int {
	return s.Rating
}

// GetOrigin returns the value of Origin.
func (s *RecordDetail) GetOrigin() OptNilString {
	return s.Origin
}

// GetRoastLevel returns the value of RoastLevel.
func (s *RecordDetail) GetRoastLevel() OptNilRecordDetailRoastLevel {
	return s.RoastLevel
}

// GetShop returns the value of Shop.
func (s *RecordDetail) GetShop() OptNilString {
	return s.Shop
}

// GetPrice returns the value of Price.
func (s *RecordDetail) GetPrice() OptNilInt {
	return s.Price
}

// GetPurchasedAt returns the value of PurchasedAt.
func (s *RecordDetail) GetPurchasedAt() OptNilDate {
	return s.PurchasedAt
}

// GetTastingNote returns the value of TastingNote.
func (s *RecordDetail) GetTastingNote() OptNilString {
	return s.TastingNote
}

// GetBrewMethod returns the value of BrewMethod.
func (s *RecordDetail) GetBrewMethod() OptNilRecordDetailBrewMethod {
	return s.BrewMethod
}

// GetRecipe returns the value of Recipe.
func (s *RecordDetail) GetRecipe() OptNilString {
	return s.Recipe
}

// GetIsNoteFilled returns the value of IsNoteFilled.
func (s *RecordDetail) GetIsNoteFilled() bool {
	return s.IsNoteFilled
}

// GetCreatedAt returns the value of CreatedAt.
func (s *RecordDetail) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *RecordDetail) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// GetRelatedRecords returns the value of RelatedRecords.
func (s *RecordDetail) GetRelatedRecords() []Record {
	return s.RelatedRecords
}

// SetID sets the value of ID.
func (s *RecordDetail) SetID(val int64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *RecordDetail) SetName(val string) {
	s.Name = val
}

// SetRating sets the value of Rating.
func (s *RecordDetail) SetRating(val int) {
	s.Rating = val
}

// SetOrigin sets the value of Origin.
func (s *RecordDetail) SetOrigin(val OptNilString) {
	s.Origin = val
}

// SetRoastLevel sets the value of RoastLevel.
func (s *RecordDetail) SetRoastLevel(val OptNilRecordDetailRoastLevel) {
	s.RoastLevel = val
}

// SetShop sets the value of Shop.
func (s *RecordDetail) SetShop(val OptNilString) {
	s.Shop = val
}

// SetPrice sets the value of Price.
func (s *RecordDetail) SetPrice(val OptNilInt) {
	s.Price = val
}

// SetPurchasedAt sets the value of PurchasedAt.
func (s *RecordDetail) SetPurchasedAt(val OptNilDate) {
	s.PurchasedAt = val
}

// SetTastingNote sets the value of TastingNote.
func (s *RecordDetail) SetTastingNote(val OptNilString) {
	s.TastingNote = val
}

// SetBrewMethod sets the value of BrewMethod.
func (s *RecordDetail) SetBrewMethod(val OptNilRecordDetailBrewMethod) {
	s.BrewMethod = val
}

// SetRecipe sets the value of Recipe.
func (s *RecordDetail) SetRecipe(val OptNilString) {
	s.Recipe = val
}

// SetIsNoteFilled sets the value of IsNoteFilled.
func (s *RecordDetail) SetIsNoteFilled(val bool) {
	s.IsNoteFilled = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *RecordDetail) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *RecordDetail) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// SetRelatedRecords sets the value of RelatedRecords.
func (s *RecordDetail) SetRelatedRecords(val []Record) {
	s.RelatedRecords = val
}

func (*RecordDetail) getRecordRes() {}

type RecordDetailBrewMethod string

const (
	RecordDetailBrewMethodDrip        RecordDetailBrewMethod = "drip"
	RecordDetailBrewMethodEspresso    RecordDetailBrewMethod = "espresso"
	RecordDetailBrewMethodFrenchPress RecordDetailBrewMethod = "french_press"
	RecordDetailBrewMethodOther       RecordDetailBrewMethod = "other"
)

// AllValues returns all RecordDetailBrewMethod values.
func (RecordDetailBrewMethod) AllValues() []RecordDetailBrewMethod {
	return []RecordDetailBrewMethod{
		RecordDetailBrewMethodDrip,
		RecordDetailBrewMethodEspresso,
		RecordDetailBrewMethodFrenchPress,
		RecordDetailBrewMethodOther,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s RecordDetailBrewMethod) MarshalText() ([]byte, error) {
	switch s {
	case RecordDetailBrewMethodDrip:
		return []byte(s), nil
	case RecordDetailBrewMethodEspresso:
		return []byte(s), nil
	case RecordDetailBrewMethodFrenchPress:
		return []byte(s), nil
	case RecordDetailBrewMethodOther:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *RecordDetailBrewMethod) UnmarshalText(data []byte) error {
	switch RecordDetailBrewMethod(data) {
	case RecordDetailBrewMethodDrip:
		*s = RecordDetailBrewMethodDrip
		return nil
	case RecordDetailBrewMethodEspresso:
		*s = RecordDetailBrewMethodEspresso
		return nil
	case RecordDetailBrewMethodFrenchPress:
		*s = RecordDetailBrewMethodFrenchPress
		return nil
	case RecordDetailBrewMethodOther:
		*s = RecordDetailBrewMethodOther
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type RecordDetailRoastLevel string

const (
	RecordDetailRoastLevelLight  RecordDetailRoastLevel = "light"
	RecordDetailRoastLevelMedium RecordDetailRoastLevel = "medium"
	RecordDetailRoastLevelDark   RecordDetailRoastLevel = "dark"
)

// AllValues returns all RecordDetailRoastLevel values.
func (RecordDetailRoastLevel) AllValues() []RecordDetailRoastLevel {
	return []RecordDetailRoastLevel{
		RecordDetailRoastLevelLight,
		RecordDetailRoastLevelMedium,
		RecordDetailRoastLevelDark,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s RecordDetailRoastLevel) MarshalText() ([]byte, error) {
	switch s {
	case RecordDetailRoastLevelLight:
		return []byte(s), nil
	case RecordDetailRoastLevelMedium:
		return []byte(s), nil
	case RecordDetailRoastLevelDark:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *RecordDetailRoastLevel) UnmarshalText(data []byte) error {
	switch RecordDetailRoastLevel(data) {
	case RecordDetailRoastLevelLight:
		*s = RecordDetailRoastLevelLight
		return nil
	case RecordDetailRoastLevelMedium:
		*s = RecordDetailRoastLevelMedium
		return nil
	case RecordDetailRoastLevelDark:
		*s = RecordDetailRoastLevelDark
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type RecordRoastLevel string

const (
	RecordRoastLevelLight  RecordRoastLevel = "light"
	RecordRoastLevelMedium RecordRoastLevel = "medium"
	RecordRoastLevelDark   RecordRoastLevel = "dark"
)

// AllValues returns all RecordRoastLevel values.
func (RecordRoastLevel) AllValues() []RecordRoastLevel {
	return []RecordRoastLevel{
		RecordRoastLevelLight,
		RecordRoastLevelMedium,
		RecordRoastLevelDark,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s RecordRoastLevel) MarshalText() ([]byte, error) {
	switch s {
	case RecordRoastLevelLight:
		return []byte(s), nil
	case RecordRoastLevelMedium:
		return []byte(s), nil
	case RecordRoastLevelDark:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *RecordRoastLevel) UnmarshalText(data []byte) error {
	switch RecordRoastLevel(data) {
	case RecordRoastLevelLight:
		*s = RecordRoastLevelLight
		return nil
	case RecordRoastLevelMedium:
		*s = RecordRoastLevelMedium
		return nil
	case RecordRoastLevelDark:
		*s = RecordRoastLevelDark
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/StatsSummary
type StatsSummary struct {
	TotalRecords int         `json:"total_records"`
	ByOrigin     []GroupStat `json:"by_origin"`
	ByRoastLevel []GroupStat `json:"by_roast_level"`
	ByBrewMethod []GroupStat `json:"by_brew_method"`
}

// GetTotalRecords returns the value of TotalRecords.
func (s *StatsSummary) GetTotalRecords() int {
	return s.TotalRecords
}

// GetByOrigin returns the value of ByOrigin.
func (s *StatsSummary) GetByOrigin() []GroupStat {
	return s.ByOrigin
}

// GetByRoastLevel returns the value of ByRoastLevel.
func (s *StatsSummary) GetByRoastLevel() []GroupStat {
	return s.ByRoastLevel
}

// GetByBrewMethod returns the value of ByBrewMethod.
func (s *StatsSummary) GetByBrewMethod() []GroupStat {
	return s.ByBrewMethod
}

// SetTotalRecords sets the value of TotalRecords.
func (s *StatsSummary) SetTotalRecords(val int) {
	s.TotalRecords = val
}

// SetByOrigin sets the value of ByOrigin.
func (s *StatsSummary) SetByOrigin(val []GroupStat) {
	s.ByOrigin = val
}

// SetByRoastLevel sets the value of ByRoastLevel.
func (s *StatsSummary) SetByRoastLevel(val []GroupStat) {
	s.ByRoastLevel = val
}

// SetByBrewMethod sets the value of ByBrewMethod.
func (s *StatsSummary) SetByBrewMethod(val []GroupStat) {
	s.ByBrewMethod = val
}

func (*StatsSummary) getStatsSummaryRes() {}

type UpdateRecordBadRequest Error

func (*UpdateRecordBadRequest) updateRecordRes() {}

type UpdateRecordInternalServerError Error

func (*UpdateRecordInternalServerError) updateRecordRes() {}

type UpdateRecordNotFound Error

func (*UpdateRecordNotFound) updateRecordRes() {}

// Ref: #/components/schemas/UpdateRecordRequest
type UpdateRecordRequest struct {
	Name        OptString                           `json:"name"`
	Rating      OptInt                              `json:"rating"`
	Origin      OptNilString                        `json:"origin"`
	RoastLevel  OptNilUpdateRecordRequestRoastLevel `json:"roast_level"`
	Shop        OptNilString                        `json:"shop"`
	Price       OptNilInt                           `json:"price"`
	PurchasedAt OptNilDate                          `json:"purchased_at"`
	TastingNote OptNilString                        `json:"tasting_note"`
	BrewMethod  OptNilUpdateRecordRequestBrewMethod `json:"brew_method"`
	Recipe      OptNilString                        `json:"recipe"`
}

// GetName returns the value of Name.
func (s *UpdateRecordRequest) GetName() OptString {
	return s.Name
}

// GetRating returns the value of Rating.
func (s *UpdateRecordRequest) GetRating() OptInt {
	return s.Rating
}

// GetOrigin returns the value of Origin.
func (s *UpdateRecordRequest) GetOrigin() OptNilString {
	return s.Origin
}

// GetRoastLevel returns the value of RoastLevel.
func (s *UpdateRecordRequest) GetRoastLevel() OptNilUpdateRecordRequestRoastLevel {
	return s.RoastLevel
}

// GetShop returns the value of Shop.
func (s *UpdateRecordRequest) GetShop() OptNilString {
	return s.Shop
}

// GetPrice returns the value of Price.
func (s *UpdateRecordRequest) GetPrice() OptNilInt {
	return s.Price
}

// GetPurchasedAt returns the value of PurchasedAt.
func (s *UpdateRecordRequest) GetPurchasedAt() OptNilDate {
	return s.PurchasedAt
}

// GetTastingNote returns the value of TastingNote.
func (s *UpdateRecordRequest) GetTastingNote() OptNilString {
	return s.TastingNote
}

// GetBrewMethod returns the value of BrewMethod.
func (s *UpdateRecordRequest) GetBrewMethod() OptNilUpdateRecordRequestBrewMethod {
	return s.BrewMethod
}

// GetRecipe returns the value of Recipe.
func (s *UpdateRecordRequest) GetRecipe() OptNilString {
	return s.Recipe
}

// SetName sets the value of Name.
func (s *UpdateRecordRequest) SetName(val OptString) {
	s.Name = val
}

// SetRating sets the value of Rating.
func (s *UpdateRecordRequest) SetRating(val OptInt) {
	s.Rating = val
}

// SetOrigin sets the value of Origin.
func (s *UpdateRecordRequest) SetOrigin(val OptNilString) {
	s.Origin = val
}

// SetRoastLevel sets the value of RoastLevel.
func (s *UpdateRecordRequest) SetRoastLevel(val OptNilUpdateRecordRequestRoastLevel) {
	s.RoastLevel = val
}

// SetShop sets the value of Shop.
func (s *UpdateRecordRequest) SetShop(val OptNilString) {
	s.Shop = val
}

// SetPrice sets the value of Price.
func (s *UpdateRecordRequest) SetPrice(val OptNilInt) {
	s.Price = val
}

// SetPurchasedAt sets the value of PurchasedAt.
func (s *UpdateRecordRequest) SetPurchasedAt(val OptNilDate) {
	s.PurchasedAt = val
}

// SetTastingNote sets the value of TastingNote.
func (s *UpdateRecordRequest) SetTastingNote(val OptNilString) {
	s.TastingNote = val
}

// SetBrewMethod sets the value of BrewMethod.
func (s *UpdateRecordRequest) SetBrewMethod(val OptNilUpdateRecordRequestBrewMethod) {
	s.BrewMethod = val
}

// SetRecipe sets the value of Recipe.
func (s *UpdateRecordRequest) SetRecipe(val OptNilString) {
	s.Recipe = val
}

type UpdateRecordRequestBrewMethod string

const (
	UpdateRecordRequestBrewMethodDrip        UpdateRecordRequestBrewMethod = "drip"
	UpdateRecordRequestBrewMethodEspresso    UpdateRecordRequestBrewMethod = "espresso"
	UpdateRecordRequestBrewMethodFrenchPress UpdateRecordRequestBrewMethod = "french_press"
	UpdateRecordRequestBrewMethodOther       UpdateRecordRequestBrewMethod = "other"
)

// AllValues returns all UpdateRecordRequestBrewMethod values.
func (UpdateRecordRequestBrewMethod) AllValues() []UpdateRecordRequestBrewMethod {
	return []UpdateRecordRequestBrewMethod{
		UpdateRecordRequestBrewMethodDrip,
		UpdateRecordRequestBrewMethodEspresso,
		UpdateRecordRequestBrewMethodFrenchPress,
		UpdateRecordRequestBrewMethodOther,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s UpdateRecordRequestBrewMethod) MarshalText() ([]byte, error) {
	switch s {
	case UpdateRecordRequestBrewMethodDrip:
		return []byte(s), nil
	case UpdateRecordRequestBrewMethodEspresso:
		return []byte(s), nil
	case UpdateRecordRequestBrewMethodFrenchPress:
		return []byte(s), nil
	case UpdateRecordRequestBrewMethodOther:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *UpdateRecordRequestBrewMethod) UnmarshalText(data []byte) error {
	switch UpdateRecordRequestBrewMethod(data) {
	case UpdateRecordRequestBrewMethodDrip:
		*s = UpdateRecordRequestBrewMethodDrip
		return nil
	case UpdateRecordRequestBrewMethodEspresso:
		*s = UpdateRecordRequestBrewMethodEspresso
		return nil
	case UpdateRecordRequestBrewMethodFrenchPress:
		*s = UpdateRecordRequestBrewMethodFrenchPress
		return nil
	case UpdateRecordRequestBrewMethodOther:
		*s = UpdateRecordRequestBrewMethodOther
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type UpdateRecordRequestRoastLevel string

const (
	UpdateRecordRequestRoastLevelLight  UpdateRecordRequestRoastLevel = "light"
	UpdateRecordRequestRoastLevelMedium UpdateRecordRequestRoastLevel = "medium"
	UpdateRecordRequestRoastLevelDark   UpdateRecordRequestRoastLevel = "dark"
)

// AllValues returns all UpdateRecordRequestRoastLevel values.
func (UpdateRecordRequestRoastLevel) AllValues() []UpdateRecordRequestRoastLevel {
	return []UpdateRecordRequestRoastLevel{
		UpdateRecordRequestRoastLevelLight,
		UpdateRecordRequestRoastLevelMedium,
		UpdateRecordRequestRoastLevelDark,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s UpdateRecordRequestRoastLevel) MarshalText() ([]byte, error) {
	switch s {
	case UpdateRecordRequestRoastLevelLight:
		return []byte(s), nil
	case UpdateRecordRequestRoastLevelMedium:
		return []byte(s), nil
	case UpdateRecordRequestRoastLevelDark:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *UpdateRecordRequestRoastLevel) UnmarshalText(data []byte) error {
	switch UpdateRecordRequestRoastLevel(data) {
	case UpdateRecordRequestRoastLevelLight:
		*s = UpdateRecordRequestRoastLevelLight
		return nil
	case UpdateRecordRequestRoastLevelMedium:
		*s = UpdateRecordRequestRoastLevelMedium
		return nil
	case UpdateRecordRequestRoastLevelDark:
		*s = UpdateRecordRequestRoastLevelDark
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
