// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateRecordOperation        OperationName = "CreateRecord"
	DeleteRecordOperation        OperationName = "DeleteRecord"
	GetRecommendOperation        OperationName = "GetRecommend"
	GetRecordOperation           OperationName = "GetRecord"
	GetStatsFlavorWordsOperation OperationName = "GetStatsFlavorWords"
	GetStatsSummaryOperation     OperationName = "GetStatsSummary"
	ListRecordsOperation         OperationName = "ListRecords"
	UpdateRecordOperation        OperationName = "UpdateRecord"
)
