// Code generated by ogen, DO NOT EDIT.
package api

type CreateRecordRes interface {
	createRecordRes()
}

type DeleteRecordRes interface {
	deleteRecordRes()
}

type GetRecommendRes interface {
	getRecommendRes()
}

type GetRecordRes interface {
	getRecordRes()
}

type GetStatsFlavorWordsRes interface {
	getStatsFlavorWordsRes()
}

type GetStatsSummaryRes interface {
	getStatsSummaryRes()
}

type GetUserinfoRes interface {
	getUserinfoRes()
}

type ListRecordsRes interface {
	listRecordsRes()
}

type UpdateRecordRes interface {
	updateRecordRes()
}
