// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"time"
)

type Record struct {
	ID           int64          `json:"id"`
	UserID       int64          `json:"user_id"`
	Name         string         `json:"name"`
	Rating       int64          `json:"rating"`
	Origin       sql.NullString `json:"origin"`
	RoastLevel   sql.NullString `json:"roast_level"`
	Shop         sql.NullString `json:"shop"`
	Price        sql.NullInt64  `json:"price"`
	PurchasedAt  sql.NullTime   `json:"purchased_at"`
	TastingNote  sql.NullString `json:"tasting_note"`
	BrewMethod   sql.NullString `json:"brew_method"`
	Recipe       sql.NullString `json:"recipe"`
	IsNoteFilled bool           `json:"is_note_filled"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type User struct {
	ID           int64          `json:"id"`
	Sub          sql.NullString `json:"sub"`
	Name         string         `json:"name"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	CreatedAt    time.Time      `json:"created_at"`
}
