// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: records.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countRecords = `-- name: CountRecords :one
SELECT COUNT(*) FROM records WHERE user_id = ?
`

func (q *Queries) CountRecords(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecords, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRecord = `-- name: CreateRecord :execlastid
INSERT INTO records (
  user_id, name, rating, origin, roast_level, shop, price,
  purchased_at, tasting_note, brew_method, recipe, is_note_filled
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateRecordParams struct {
	UserID       int64          `json:"user_id"`
	Name         string         `json:"name"`
	Rating       int64          `json:"rating"`
	Origin       sql.NullString `json:"origin"`
	RoastLevel   sql.NullString `json:"roast_level"`
	Shop         sql.NullString `json:"shop"`
	Price        sql.NullInt64  `json:"price"`
	PurchasedAt  sql.NullTime   `json:"purchased_at"`
	TastingNote  sql.NullString `json:"tasting_note"`
	BrewMethod   sql.NullString `json:"brew_method"`
	Recipe       sql.NullString `json:"recipe"`
	IsNoteFilled bool           `json:"is_note_filled"`
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createRecord,
		arg.UserID,
		arg.Name,
		arg.Rating,
		arg.Origin,
		arg.RoastLevel,
		arg.Shop,
		arg.Price,
		arg.PurchasedAt,
		arg.TastingNote,
		arg.BrewMethod,
		arg.Recipe,
		arg.IsNoteFilled,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteRecord = `-- name: DeleteRecord :exec
DELETE FROM records WHERE id = ? AND user_id = ?
`

type DeleteRecordParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteRecord(ctx context.Context, arg DeleteRecordParams) error {
	_, err := q.db.ExecContext(ctx, deleteRecord, arg.ID, arg.UserID)
	return err
}

const getRecord = `-- name: GetRecord :one
SELECT id, user_id, name, rating, origin, roast_level, shop, price, purchased_at, tasting_note, brew_method, recipe, is_note_filled, created_at, updated_at FROM records WHERE id = ? AND user_id = ? LIMIT 1
`

type GetRecordParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetRecord(ctx context.Context, arg GetRecordParams) (Record, error) {
	row := q.db.QueryRowContext(ctx, getRecord, arg.ID, arg.UserID)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Rating,
		&i.Origin,
		&i.RoastLevel,
		&i.Shop,
		&i.Price,
		&i.PurchasedAt,
		&i.TastingNote,
		&i.BrewMethod,
		&i.Recipe,
		&i.IsNoteFilled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRelatedRecords = `-- name: GetRelatedRecords :many
SELECT id, user_id, name, rating, origin, roast_level, shop, price, purchased_at, tasting_note, brew_method, recipe, is_note_filled, created_at, updated_at FROM records WHERE user_id = ? AND id != ? AND name = ? ORDER BY created_at DESC LIMIT 10
`

type GetRelatedRecordsParams struct {
	UserID int64  `json:"user_id"`
	ID     int64  `json:"id"`
	Name   string `json:"name"`
}

func (q *Queries) GetRelatedRecords(ctx context.Context, arg GetRelatedRecordsParams) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, getRelatedRecords, arg.UserID, arg.ID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Record{}
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Rating,
			&i.Origin,
			&i.RoastLevel,
			&i.Shop,
			&i.Price,
			&i.PurchasedAt,
			&i.TastingNote,
			&i.BrewMethod,
			&i.Recipe,
			&i.IsNoteFilled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTastingNotes = `-- name: ListAllTastingNotes :many
SELECT tasting_note FROM records WHERE user_id = ? AND tasting_note IS NOT NULL AND tasting_note != ''
`

func (q *Queries) ListAllTastingNotes(ctx context.Context, userID int64) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listAllTastingNotes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var tasting_note sql.NullString
		if err := rows.Scan(&tasting_note); err != nil {
			return nil, err
		}
		items = append(items, tasting_note)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecords = `-- name: ListRecords :many
SELECT id, user_id, name, rating, origin, roast_level, shop, price, purchased_at, tasting_note, brew_method, recipe, is_note_filled, created_at, updated_at FROM records WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListRecords(ctx context.Context, userID int64) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, listRecords, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Record{}
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Rating,
			&i.Origin,
			&i.RoastLevel,
			&i.Shop,
			&i.Price,
			&i.PurchasedAt,
			&i.TastingNote,
			&i.BrewMethod,
			&i.Recipe,
			&i.IsNoteFilled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordsByBrewMethod = `-- name: ListRecordsByBrewMethod :many
SELECT id, user_id, name, rating, origin, roast_level, shop, price, purchased_at, tasting_note, brew_method, recipe, is_note_filled, created_at, updated_at FROM records WHERE user_id = ? AND brew_method = ? ORDER BY created_at DESC
`

type ListRecordsByBrewMethodParams struct {
	UserID     int64          `json:"user_id"`
	BrewMethod sql.NullString `json:"brew_method"`
}

func (q *Queries) ListRecordsByBrewMethod(ctx context.Context, arg ListRecordsByBrewMethodParams) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, listRecordsByBrewMethod, arg.UserID, arg.BrewMethod)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Record{}
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Rating,
			&i.Origin,
			&i.RoastLevel,
			&i.Shop,
			&i.Price,
			&i.PurchasedAt,
			&i.TastingNote,
			&i.BrewMethod,
			&i.Recipe,
			&i.IsNoteFilled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordsByOrigin = `-- name: ListRecordsByOrigin :many
SELECT id, user_id, name, rating, origin, roast_level, shop, price, purchased_at, tasting_note, brew_method, recipe, is_note_filled, created_at, updated_at FROM records WHERE user_id = ? AND origin = ? ORDER BY created_at DESC
`

type ListRecordsByOriginParams struct {
	UserID int64          `json:"user_id"`
	Origin sql.NullString `json:"origin"`
}

func (q *Queries) ListRecordsByOrigin(ctx context.Context, arg ListRecordsByOriginParams) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, listRecordsByOrigin, arg.UserID, arg.Origin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Record{}
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Rating,
			&i.Origin,
			&i.RoastLevel,
			&i.Shop,
			&i.Price,
			&i.PurchasedAt,
			&i.TastingNote,
			&i.BrewMethod,
			&i.Recipe,
			&i.IsNoteFilled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordsByRatingMin = `-- name: ListRecordsByRatingMin :many
SELECT id, user_id, name, rating, origin, roast_level, shop, price, purchased_at, tasting_note, brew_method, recipe, is_note_filled, created_at, updated_at FROM records WHERE user_id = ? AND rating >= ? ORDER BY created_at DESC
`

type ListRecordsByRatingMinParams struct {
	UserID int64 `json:"user_id"`
	Rating int64 `json:"rating"`
}

func (q *Queries) ListRecordsByRatingMin(ctx context.Context, arg ListRecordsByRatingMinParams) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, listRecordsByRatingMin, arg.UserID, arg.Rating)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Record{}
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Rating,
			&i.Origin,
			&i.RoastLevel,
			&i.Shop,
			&i.Price,
			&i.PurchasedAt,
			&i.TastingNote,
			&i.BrewMethod,
			&i.Recipe,
			&i.IsNoteFilled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordsByRoastLevel = `-- name: ListRecordsByRoastLevel :many
SELECT id, user_id, name, rating, origin, roast_level, shop, price, purchased_at, tasting_note, brew_method, recipe, is_note_filled, created_at, updated_at FROM records WHERE user_id = ? AND roast_level = ? ORDER BY created_at DESC
`

type ListRecordsByRoastLevelParams struct {
	UserID     int64          `json:"user_id"`
	RoastLevel sql.NullString `json:"roast_level"`
}

func (q *Queries) ListRecordsByRoastLevel(ctx context.Context, arg ListRecordsByRoastLevelParams) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, listRecordsByRoastLevel, arg.UserID, arg.RoastLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Record{}
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Rating,
			&i.Origin,
			&i.RoastLevel,
			&i.Shop,
			&i.Price,
			&i.PurchasedAt,
			&i.TastingNote,
			&i.BrewMethod,
			&i.Recipe,
			&i.IsNoteFilled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecord = `-- name: UpdateRecord :exec
UPDATE records SET
  name          = ?,
  rating        = ?,
  origin        = ?,
  roast_level   = ?,
  shop          = ?,
  price         = ?,
  purchased_at  = ?,
  tasting_note  = ?,
  brew_method   = ?,
  recipe        = ?,
  is_note_filled = ?,
  updated_at    = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
`

type UpdateRecordParams struct {
	Name         string         `json:"name"`
	Rating       int64          `json:"rating"`
	Origin       sql.NullString `json:"origin"`
	RoastLevel   sql.NullString `json:"roast_level"`
	Shop         sql.NullString `json:"shop"`
	Price        sql.NullInt64  `json:"price"`
	PurchasedAt  sql.NullTime   `json:"purchased_at"`
	TastingNote  sql.NullString `json:"tasting_note"`
	BrewMethod   sql.NullString `json:"brew_method"`
	Recipe       sql.NullString `json:"recipe"`
	IsNoteFilled bool           `json:"is_note_filled"`
	ID           int64          `json:"id"`
	UserID       int64          `json:"user_id"`
}

func (q *Queries) UpdateRecord(ctx context.Context, arg UpdateRecordParams) error {
	_, err := q.db.ExecContext(ctx, updateRecord,
		arg.Name,
		arg.Rating,
		arg.Origin,
		arg.RoastLevel,
		arg.Shop,
		arg.Price,
		arg.PurchasedAt,
		arg.TastingNote,
		arg.BrewMethod,
		arg.Recipe,
		arg.IsNoteFilled,
		arg.ID,
		arg.UserID,
	)
	return err
}
