// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const avgRatingByName = `-- name: AvgRatingByName :one
SELECT AVG(rating) FROM records WHERE user_id = ? AND name = ?
`

type AvgRatingByNameParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) AvgRatingByName(ctx context.Context, arg AvgRatingByNameParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, avgRatingByName, arg.UserID, arg.Name)
	var avg interface{}
	err := row.Scan(&avg)
	return avg, err
}

const avgRatingByOrigin = `-- name: AvgRatingByOrigin :one
SELECT AVG(rating) FROM records WHERE user_id = ? AND origin = ?
`

type AvgRatingByOriginParams struct {
	UserID int64          `json:"user_id"`
	Origin sql.NullString `json:"origin"`
}

func (q *Queries) AvgRatingByOrigin(ctx context.Context, arg AvgRatingByOriginParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, avgRatingByOrigin, arg.UserID, arg.Origin)
	var avg interface{}
	err := row.Scan(&avg)
	return avg, err
}

const statsByBrewMethod = `-- name: StatsByBrewMethod :many
SELECT
  brew_method AS label,
  COUNT(*) AS count,
  AVG(rating) AS avg_rating
FROM records
WHERE user_id = ? AND brew_method IS NOT NULL AND brew_method != ''
GROUP BY brew_method
ORDER BY avg_rating DESC
`

type StatsByBrewMethodRow struct {
	Label     sql.NullString `json:"label"`
	Count     int64          `json:"count"`
	AvgRating interface{}    `json:"avg_rating"`
}

func (q *Queries) StatsByBrewMethod(ctx context.Context, userID int64) ([]StatsByBrewMethodRow, error) {
	rows, err := q.db.QueryContext(ctx, statsByBrewMethod, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsByBrewMethodRow{}
	for rows.Next() {
		var i StatsByBrewMethodRow
		if err := rows.Scan(&i.Label, &i.Count, &i.AvgRating); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsByOrigin = `-- name: StatsByOrigin :many
SELECT
  origin AS label,
  COUNT(*) AS count,
  AVG(rating) AS avg_rating
FROM records
WHERE user_id = ? AND origin IS NOT NULL AND origin != ''
GROUP BY origin
ORDER BY avg_rating DESC
`

type StatsByOriginRow struct {
	Label     sql.NullString `json:"label"`
	Count     int64          `json:"count"`
	AvgRating interface{}    `json:"avg_rating"`
}

func (q *Queries) StatsByOrigin(ctx context.Context, userID int64) ([]StatsByOriginRow, error) {
	rows, err := q.db.QueryContext(ctx, statsByOrigin, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsByOriginRow{}
	for rows.Next() {
		var i StatsByOriginRow
		if err := rows.Scan(&i.Label, &i.Count, &i.AvgRating); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsByRoastLevel = `-- name: StatsByRoastLevel :many
SELECT
  roast_level AS label,
  COUNT(*) AS count,
  AVG(rating) AS avg_rating
FROM records
WHERE user_id = ? AND roast_level IS NOT NULL AND roast_level != ''
GROUP BY roast_level
ORDER BY avg_rating DESC
`

type StatsByRoastLevelRow struct {
	Label     sql.NullString `json:"label"`
	Count     int64          `json:"count"`
	AvgRating interface{}    `json:"avg_rating"`
}

func (q *Queries) StatsByRoastLevel(ctx context.Context, userID int64) ([]StatsByRoastLevelRow, error) {
	rows, err := q.db.QueryContext(ctx, statsByRoastLevel, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsByRoastLevelRow{}
	for rows.Next() {
		var i StatsByRoastLevelRow
		if err := rows.Scan(&i.Label, &i.Count, &i.AvgRating); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
