// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const ensureDefaultUser = `-- name: EnsureDefaultUser :exec
INSERT IGNORE INTO users (id, name, email, password_hash)
VALUES (1, 'default', 'default@beanmemo.local', 'n/a')
`

func (q *Queries) EnsureDefaultUser(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, ensureDefaultUser)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, sub, name, email, password_hash, created_at FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Sub,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserBySub = `-- name: GetUserBySub :one
SELECT id, sub, name, email, password_hash, created_at FROM users WHERE sub = ? LIMIT 1
`

func (q *Queries) GetUserBySub(ctx context.Context, sub sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserBySub, sub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Sub,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUserBySub = `-- name: UpsertUserBySub :exec
INSERT INTO users (sub, name, email, password_hash)
VALUES (?, ?, '', 'n/a')
ON DUPLICATE KEY UPDATE name = VALUES(name)
`

type UpsertUserBySubParams struct {
	Sub  sql.NullString `json:"sub"`
	Name string         `json:"name"`
}

func (q *Queries) UpsertUserBySub(ctx context.Context, arg UpsertUserBySubParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserBySub, arg.Sub, arg.Name)
	return err
}
