// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"
)

const ensureDefaultUser = `-- name: EnsureDefaultUser :exec
INSERT IGNORE INTO users (id, name, email, password_hash)
VALUES (1, 'default', 'default@beanmemo.local', 'n/a')
`

func (q *Queries) EnsureDefaultUser(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, ensureDefaultUser)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, password_hash, created_at FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
